version: '3.9'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: tccoin/docker-ros:ros
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  camera:
    image: tccoin/docker-ros
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    privileged: true
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
    stdin_open: true
    tty: true
    entrypoint: /bin/bash -c "source ~/catkin_ws/devel/setup.bash && roslaunch galaxy_camera MER-139.launch"

  vnc:
    image: tccoin/docker-ros
    depends_on:
      - ros-master
    container_name: vnc
    networks:
      - ros
    environment:
      - "VNC_PASSWORD=rv6666"
      - "VNC_RESOLUTION=1280x720"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "5900:5900"
      - "6900:80"
    privileged: true
    volumes:
      - ./ws:/root/ws:rw
      - ./ws/zsh/.zshrc:/root/.zshrc:rw
      - ./ws/zsh/.zsh_history:/root/.zsh_history:rw
      - ./ws/config/.gtkrc-2.0.mine:/root/.gtkrc-2.0.mine:rw
      - ./ws/config/rc.xml:/root/.config/openbox/rc.xml:rw
      - ./ws/config/tilix.dconf:/root/tilix.dconf:rw
      - ./ws/script/vnc.sh:/root/vnc.sh:rw
    stdin_open: true
    tty: true
    entrypoint: /root/vnc.sh
    