version: '3.9'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: osrf/ros:noetic-desktop-full
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  camera:
    image: tccoin/docker-ros
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    privileged: true
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
    stdin_open: true
    tty: true
    entrypoint: /bin/bash -c "source ~/catkin_ws/devel/setup.bash && roslaunch galaxy_camera MER-139.launch"

  vnc:
    image: tccoin/docker-ros
    depends_on:
      - ros-master
    container_name: vnc
    networks:
      - ros
    environment:
      - "VNC_PW=rv666"
      - "VNC_RESOLUTION=1280x1024"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "5901:5901"
      - "6901:6901"
    privileged: true
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - ../ws:/root/ws:rw
      - ../ws/zsh/.zshrc:/root/.zshrc:rw
      - ../ws/zsh/.zsh_history:/root/.zsh_history:rw
    stdin_open: true
    tty: true
    entrypoint: /bin/bash -c "(nohup /dockerstartup/vnc_startup.sh> vnc.log & ) && /bin/zsh"