version: '3.9'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: tccoin/docker-ros:ros
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  camera:
    image: tccoin/docker-ros
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    privileged: true
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
    stdin_open: true
    tty: true
    entrypoint: /bin/bash -c "source ~/catkin_ws/devel/setup.bash && roslaunch galaxy_camera MER-139.launch"

  vnc:
    image: tccoin/docker-ros
    depends_on:
      - ros-master
    container_name: vnc
    networks:
      - ros
    environment:
      - "VNC_PASSWORD=rv6666"
      - "VNC_RESOLUTION=1280x720"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "5900:5900"
      - "6900:80"
    privileged: true
    volumes:
      - ./ws:/root/ws:rw
      - ./ws/zsh/.zshrc:/root/.zshrc:rw
      - ./ws/zsh/.zsh_history:/root/.zsh_history:rw
      - ./ws/config/.gtkrc-2.0.mine:/root/.gtkrc-2.0.mine:rw
      - ./ws/config/rc.xml:/root/.config/openbox/rc.xml:rw
      - ./ws/config/tilix.dconf:/root/tilix.dconf:rw
      - ./ws/script/vnc.sh:/root/vnc.sh:rw
    stdin_open: true
    tty: true
    entrypoint: /root/vnc.sh
    
  node-bridge:
    image: tccoin/docker-ros
    depends_on:
      - ros-master
    container_name: node-bridge
    networks:
      - ros
    environment:
      - "VNC_PASSWORD=rv6666"
      - "VNC_RESOLUTION=1280x720"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "5900:5900"
      - "6900:80"
    privileged: true
    volumes:
      - ./ws:/root/ws:rw
      - ./ws/zsh/.zshrc:/root/.zshrc:rw
      - ./ws/zsh/.zsh_history:/root/.zsh_history:rw
      - ./ws/config/.gtkrc-2.0.mine:/root/.gtkrc-2.0.mine:rw
      - ./ws/config/rc.xml:/root/.config/openbox/rc.xml:rw
      - ./ws/config/tilix.dconf:/root/tilix.dconf:rw
      - ./ws/script/vnc.sh:/root/vnc.sh:rw
      - ./ws/node-bridge-ros:/root/catkin_ws/src/node_bridge_ros:rw
      - ./ws/node-bridge:/root/catkin_ws/src/node_bridge_ros/include/node_bridge/:rw
    stdin_open: true
    tty: true
    entrypoint: /root/vnc.sh
    
  mynt:
    image: tccoin/docker-ros
    depends_on:
      - ros-master
    container_name: mynt
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    privileged: true
    entrypoint: /bin/bash -c "source /root/build/mynt-eye-d-sdk/wrappers/ros/devel/setup.bash && roslaunch mynteye_wrapper_d mynteye.launch left_color_topic:=/camera/left/image_raw right_color_topic:=/camera/right/image_raw ir_intensity:=0" 
    
  slam:
    image: tccoin/docker-ros:slam
    depends_on:
      - ros-master
    container_name: slam
    networks:
      - ros
    environment:
      - "VNC_PASSWORD=rv6666"
      - "VNC_RESOLUTION=1920x1080"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "5900:5900"
      - "6900:80"
    privileged: true
    volumes:
      - ./ws:/root/ws:rw
      - ./ws/zsh/.zshrc:/root/.zshrc:rw
      - ./ws/zsh/.zsh_history:/root/.zsh_history:rw
      - ./ws/config/.gtkrc-2.0.mine:/root/.gtkrc-2.0.mine:rw
      - ./ws/config/rc.xml:/root/.config/openbox/rc.xml:rw
      - ./ws/config/tilix.dconf:/root/tilix.dconf:rw
      - ./ws/node-bridge-ros:/root/catkin_ws/src/node_bridge_ros:rw
      - ./ws/node-bridge:/root/catkin_ws/src/node_bridge_ros/include/node_bridge/:rw
      - ./ws/script/slam.sh:/root/slam.sh:rw
    entrypoint: /root/slam.sh

  kinect:
    image: tccoin/docker-ros:kinect
    container_name: kinect
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    privileged: true
    volumes: 
      #share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/lib/x86_64-linux-gnu/libXv.so.1:/usr/lib/x86_64-linux-gnu/libXv.so.1
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
    entrypoint: /bin/bash -c "source /opt/ros/noetic/local_setup.bash && source /root/ws/install/local_setup.bash && roslaunch --wait kinect2_bridge kinect2_bridge.launch"

  rosbridge:
    image: tccoin/docker-ros
    container_name: rosbridge
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9090:9090"
    networks:
      - ros
    entrypoint: /bin/bash -c "source /opt/ros/noetic/setup.bash && roslaunch rosbridge_server rosbridge_websocket.launch"

  webviz:
    image: cruise/webviz
    container_name: webviz
    depends_on:
      - rosbridge
    ports:
      - "7900:8080"